name: Deploy Flask App

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout codes
      uses: actions/checkout@v3
      
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.5.7"
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
        aws-sdk-version: '3'  # Suppress SDK v2 warning
        
    - name: Terraform Init and Apply
      run: |
        cd terraform
        terraform init
        terraform validate
        terraform destroy -auto-approve
        
        
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
        
    - name: Deploy Flask App
      uses: appleboy/ssh-action@master
      with:
          host: ${{ steps.get-ip.outputs.IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Install Docker if needed
            if ! command -v docker &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo usermod -aG docker ubuntu
            fi
            
            # Prepare app directory
            sudo rm -rf /home/ubuntu/app
            mkdir -p /home/ubuntu/app
            
            # Copy app files
            scp -r -o StrictHostKeyChecking=no ./app/* ubuntu@${{ steps.get-ip.outputs.IP }}:/home/ubuntu/app/
            
            # Build and run container
            cd /home/ubuntu/app
            sudo docker build -t flask-app .
            sudo docker stop flask-container || true
            sudo docker rm flask-container || true
            sudo docker run -d -p 80:80 --name flask-container flask-app