name: Deploy Flask App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Terraform Apply
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve
        
    - name: Get Instance IP
      id: get-ip
      run: |
        cd terraform
        echo "IP=$(terraform output -raw instance_public_ip)" >> $GITHUB_OUTPUT
        
    - name: Deploy Flask App
      uses: appleboy/ssh-action@master
      with:
        host: ${{ steps.get-ip.outputs.IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Copy app files
          sudo rm -rf /home/ubuntu/app/*
          sudo chown -R ubuntu:ubuntu /home/ubuntu/app
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 400 key.pem
          scp -o StrictHostKeyChecking=no -i key.pem -r ./app/* ubuntu@${{ steps.get-ip.outputs.IP }}:/home/ubuntu/app/
          
          # Build and run Docker container
          cd /home/ubuntu/app
          sudo docker build -t flask-app .
          sudo docker stop flask-container || true
          sudo docker rm flask-container || true
          sudo docker run -d -p 80:80 --name flask-container flask-app