name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform command to run (init, plan, apply, destroy)"
        required: true
        default: "apply"
        type: choice
        options:
          - "init"
          - "plan"
          - "apply"
          - "destroy"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0

      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Terraform Init
        if: inputs.action == 'init'
        run: terraform init

      - name: Terraform Plan
        if: inputs.action == 'plan'
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        if: inputs.action == 'apply'
        run: terraform apply -auto-approve -var-file="terraform.tfvars"

      - name: Terraform Destroy
        if: inputs.action == 'destroy'
        run: terraform destroy -auto-approve -var-file="terraform.tfvars"
