name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform command to run (plan, apply, destroy)"
        required: true
        default: "apply"
        type: choice
        options:
          - "plan"
          - "apply"
          - "destroy"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0

      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Create terraform.tfvars
        run: echo "${{ secrets.TFVARS }}" > terraform.tfvars

      - name: Terraform Plans
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'plan'
        run: |
          terraform init -upgrade
          terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply' || github.event_name == 'push'
        run: |
          terraform init -upgrade
          terraform apply -auto-approve -var-file="terraform.tfvars"

      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: |
          terraform init -upgrade
          terraform destroy -auto-approve -var-file="terraform.tfvars"
